add 3
ech-world/ech-projects pull request #1
Opened 2022-09-05 07:56 UTC by ftm1337

# to-do (further)
- [x] add pics
- [ ] add ecswap
- [ ] add radio
- [ ] add restake.app
- [ ] add Guru DAO

2022-09-05 08:16 UTC, ech-world commented on projects/beethovenx.md
> +[![Beets](/_images/cover_beethovenx.png "1ECH")](https://beets,fi)
Fix link, change comma to dot: https://beets.fi

2022-09-05 08:20 UTC, ech-world commented on projects/defillama.md
> +post_excerpt: DefiLlama is a DeFi TVL aggregator. It is committed to providing accurate data without ads or sponsored content, as well as transparency.
Please shorten a bit so it will fit better on the Projects list box, suggestion: DefiLlama is DeFi TVL aggregator committed to providing accurate data with transparency and without ads

2022-09-05 08:22 UTC, ech-world commented on projects/beethovenx.md
> +post_excerpt:  Built on Balancer V2, Beethoven X is the first next-generation AMM protocol on Fantom Opera & Optimism.
Please remove dot from the end of post_excerpt, thanks :)

2022-09-05 08:27 UTC, ech-world requested changes
Thank you very much for your contribution!! :) Please check the small comments/suggestions in .md's. Also, please downscale echguru.png to about 500x500 so we can keep Project list (shows all logos) loading nice and fast, thanks!

2022-09-05 08:31 UTC, ech-world commented on projects/defillama.md
> +DefiLlama provides live data for over 120 blockchains including Echelon. There are also different levels of [APIs](https://www.coingecko.com/en/api) that have public endpoints for live and historical
API link goes to coingecko, this would be changed to: https://defillama.com/docs/api

2022-10-16 12:00 UTC, ftm1337 commented
hi @ech-world :wave: 
sorry for the delay, updated this according to your notes :)

2022-10-16 12:28 UTC, ech-world reviewed
Fixes ok, thanks @ftm1337 :), publishing

2022-10-16 12:31 UTC, merged